apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-demo
  namespace: ads-demo
spec:
  replicas: 2
  selector:
    matchLabels: { app: ads-demo }
  template:
    metadata:
      labels: { app: ads-demo }
    spec:
      containers:
        - name: app
          image: ghcr.io/OWNER/ads-demo:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ads-demo
                  key: DATABASE_URL
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Namespace
metadata:
  name: ads-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: ads-demo
  namespace: ads-demo
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ads:change_me@postgres.default.svc.cluster.local:5432/adsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: ads-demo
  namespace: ads-demo
spec:
  selector: { app: ads-demo }
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ads-demo
  namespace: ads-demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ads-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ads-demo
                port:
                  number: 80