- name: Create app directory
  file: { path: /opt/ads-demo, state: directory }

- name: Create docker-compose.yaml
  copy:
    dest: /opt/ads-demo/docker-compose.yaml
    content: |
      services:
        app:
          image: "{{ app_image }}"
          restart: always
          environment:
            DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@{{ hostvars[groups['db'][0]].ansible_host }}:5432/{{ db_name }}"
          ports: [ "80:8000" ]

- name: Compose up
  community.docker.docker_compose_v2:
    project_src: /opt/ads-demo
    state: present